### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by svetlyak40wt** [nzt/cl-pov#2]
I thought about something like that today. And found you project by accidentally only because had UFO opened in the tab and decided to look at other you projects.

Are you using cl-pov for something or it is just a toy?

**Comment by tani** [comment]
Thanks, @svetlyak40wt !

cl-pov is just a toy.
I used a POV-Ray when I taught  programming to my friends, because CG art programming is good for beginners.
But POV-Ray is not good as programming language.

I thought and made it.

Commonlisp's macro system is better than POV-Rray's. `examples/logo.lisp` is a good example.
We can use `defun` and `defvar`, `defmacro` in cl-pov.
